name: Build and Push Docker Image to ACR

on:
  release:
    types: [published]
    branches:
      - main

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  ACR_REPOSITORY: ${{ secrets.ACR_REPOSITORY }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: |
          echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin

      - name: Build and Push Windows Docker Image
        run: |
          docker build -t $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$RELEASE_TAG-windows -f Dockerfile.windows .
          docker push $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$RELEASE_TAG-windows

      - name: Log out from ACR
        run: docker logout $ACR_LOGIN_SERVER

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: |
          echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin

      - name: Build Linux Docker Image
        run: docker build -t $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$RELEASE_TAG-linux -f Dockerfile.linux .

      - name: Log out from ACR
        run: docker logout $ACR_LOGIN_SERVER

  multi-platform-image:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        run: |
          echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin

      - name: Create Multi-Platform Image
        run: |
          docker buildx imagetools create --tag $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$RELEASE_TAG \
            $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$RELEASE_TAG-windows
          docker buildx imagetools create --tag $ACR_LOGIN_SERVER/$ACR_REPOSITORY:latest \
            $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$RELEASE_TAG-windows

      - name: Log out from ACR
        run: docker logout $ACR_LOGIN_SERVER
