name: Build Docker Image

on:
  release:
    types: [published]
    branches:
      - lildeng/docker_release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t lisa-image:${{ github.event.release.tag_name }} .
